### PR TITLE
Neils reworking

### LINKED ISSUE #1: Warning: Error in if: missing value where TRUE/FALSE needed
```
Warning: Error in if: missing value where TRUE/FALSE needed
  212: eventReactiveHandler [/Users/rpc5102/Workspaces/R/Hypothesis_Testing/server.R#255]
  210: handlerFunc
  197: func
  195: f
  194: Reduce
  185: do
  184: hybrid_chain
  183: <reactive>
  182: .func
  179: contextFunc
  178: env$runWith
  171: ctx$run
  170: self$.updateValue
  168: phat
  167: renderPlot [/Users/rpc5102/Workspaces/R/Hypothesis_Testing/server.R#320]
  165: func
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$proportion2NBA
    1: runApp
```
Screen Shot 2019-12-04 at 2 01 47 PM

### LINKED ISSUE #2: Input to asJSON(keep_vec_names=TRUE) is a named vector.
`Using hypothesis as id variables
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.`

Occurs when creating sample plot.

### LINKED ISSUE #3: Out of date datasets
Datasets used should remain up to date. To avoid updating the data every season, consider utilizing Hall of Fame or All Star data.

### LINKED ISSUE #4: User Input Enhancement
Screen Shot 2020-05-20 at 10 45 30 AM

A slider input with limits (0,1.00) would be more appropriate than a numeric input because a value greater than 1 gives an error for the exact hypothesis test.
Edit: This input is in the hypothesis testing section of the app if it wasn't clear.

### LINKED ISSUE #5: Error message revision
Screen Shot 2020-05-20 at 11 03 21 AM

Here, the app displays an error message because both end of the slider are set to one number. The same error is displayed when 0 is selected. Rather than a general error message, try informing the user that there are no players in the dataset that satisfy that filter, or something to that extent.

### LINKED ISSUE #7: Warning Message Reported
The following warning is printed to the console:
    Warning in max(dat[which(dat < (h0 - 1.96 * stanerr1))]) :
      no non-missing arguments to max; returning -Inf

I get this message whenever I ask for the significance bounds to be plotted and the change the null hypothesis value slider to ≤ 0.16 OR ≥ 0.84

### LINKED ISSUE #8: Significance Bounds Improperly Calculated
The significance bounds are currently being centered around the null hypothesis value rather than the point estimate (p-hat). This needs to get updated. (See lines 449-454 in the server.

### LINKED ISSUE #9: Warning
When testing the app out I received the following warning message:
```
Warning in base::min(x, ..., na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
```
Re-creation path: Challenge Page->[Manual] Select Player->Al Horford->H0 = 0.43 -> n <= 19 (experiments also showed n = 25)

### PR DESCRIPTION
**Pull request by neilhatfield**
Competes with #6 
This branch builds off of the DevDemo branch, with a switch over the the app.R framework and a near complete re-imagining of the server code.

Issues Resolved with this Pull Request:
Fixes #1 
Closes #2 
Fixes #3 
Fixes #4 
Fixes #5 
Fixes #7 
Fixes #8 
Fixes #9 

Will Close #6 if adopted

### CODE REVIEW

**Review by NurulSyafiqah-pixel — CHANGES_REQUESTED** [review]
1) The README file in dev branch does not have badges. 

Recommended Priority: Urgent

**Review by tarynmch — CHANGES_REQUESTED** [review]
Good app and very educational, I just had a few comments and noticed one bug. The description file should be updated, particularly the authors and year. The cover photo in the README file also should be updated along with the year badge (docs and todo file should also be created).  Cite this app information is also missing at the bottom of the overview page. I also do not see alt text for the plots. The bug I noticed is on the testing page. I chose a player then clicked simulate. Then I tried choosing "Pick for me" and since the simulate button does not appear, I cannot simulate it. While I can simulate other players, I cannot choose "Pick for me" again because the choose button does not refresh. My recommendations are to make the prerequisites page a little more descriptive. Then I do think the data is something that needs to be updated frequently which is just something to consider for future reference.

**Review by robchapp — CHANGES_REQUESTED** [review]
Off of what Taryn said, there needs to be a docs folder using the screenshot, readme, and license files. Also a button to the prerequisites page should be added to the overview page. Also off of the bug Taryn found a possible solution could be to add a button to pick a random player. In description a tag could be sports, along with the year being incorrect in the readme file. There is no cite as, and the authors are wrong in the description file. Otherwise I think the app is great.

**Review by tarynmch — CHANGES_REQUESTED** [review]
Looks good with the updated data. If you do update the data, be sure to update the references tab with where you got your data and on the Testing tab update the years that the data is from (both still say 18-19). There is also still the bug on the Testing page. Once you click Simulate, the Choose button does not work. You are not able to choose the Pick for me option twice, you would have to refresh the page. There is also missing links below the Penn State logo. It is the "Contact | Privacy | Accessibility" links, you can just copy the right code from the template to fix that. On the instructions section, "Filtering, Hypothesis tests, and confidence intervals", if you capitalize some of them, I suggest capitalizing them all. Otherwise, the only other thing I noticed was that there were a lot of blue icons on the left (where the line numbers are), those are just telling you that you need white spaces there.

**Review by tarynmch — CHANGES_REQUESTED** [review]
Looks good! It works well, I just suggest editing some things on the coding side. You can delete the comments on line 394 and 395. Then look at the blue icons where the line numbers are, there needs to be white spaces in those lines. Finally, just make sure arguments within a function are written out if they are need like eventExpr and handlerExpr within an observe. Otherwise, it looks great and should be ready!

**Review by tarynmch — CHANGES_REQUESTED** [review]
Looks good. The only thing I noticed was that you have a reference for "stringr" but it is not in the libraries, so it can be deleted. I also suggest that because the definitions are so short on the prereq that they do not need their own boxes. I think bullet points would be good enough.

**Review by tarynmch — DISMISSED** [review]
Looks good! Great work.

**Comment by neilhatfield** [comment]
@robchapp 
I decided to use this app to test out a different approach to reactivity. Please pull the latest update and test out thoroughly to ensure I did not introduce any issues. Let me know of any issues.
Additionally, double check that [Issues](https://github.com/EducationShinyAppTeam/Hypothesis_Testing/issues) that have been addressed are attached to this pull request.

**Comment by robchapp** [comment]
@neilhatfield closed all issues and everything works well, alt text and reset of graphs works well still.

**Pull request merged**
